### PR TITLE
Add CloudFormation template

### PR DESCRIPTION
**Pull request by benbridts**
*Issue #, if available:*  #10

*Description of changes:* Add a CloudFormation (SAM) template to deploy cfn-guard-lambda

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ikben** [comment]
I made this as a draft, because it might make sense to replace the current deploy and test method completely with SAM.

**Comment by JustinKuskowski** [comment]
I really like having the option to deploy this via SAM. +1

**Comment by gandhek** [comment]
@benbridts I understand that this PR is in draft mode but I wanted to see if you're interested in adding SAM support for Guard 2.0? Since this PR is for 1.0, it might make sense to close this one and track SAM integration as an enhancement. Thoughts?

**Comment by gandhek** [comment]
@benbridts pinging once again to check if you want to add this support. If not, we are happy to track this in our backlog and close this PR

**Comment by benbridts** [comment]
@gandhek Thanks for the reminder, I missed the first one. I don't have time in the short term to work on this, so feel free to close it and reference it as a possible starting point in any issues that would track this feature request

**Comment by gandhek** [comment]
Closing in favor of #172

**Pull request closed without merging**
